//Tasks
export const FETCHING_TASKS = 'FETCHING_TASKS'
export const FETCHING_TASKS_SUCCESS = 'FETCHING_TASKS_SUCCESS'
export const FETCHING_TASKS_FAILURE = 'FETCHING_TASKS_FAILURE'
export const REMOVE_FETCHING_TASKS = 'REMOVE_FETCHING_TASKS'
export const UPDATE_NEWTASK_TEXT = 'UPDATE_NEWTASK_TEXT'
