//User
export const FETCHING_USER = 'FETCHING_USER';
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS';
export const FETCHING_USER_FAILURE = 'FETCHING_USER_FAILURE';
export const REMOVE_FETCHING_USER = 'REMOVE_FETCHING_USER';
export const FETCHING_USER_PATIENT = 'FETCHING_USER_PATIENT';
export const FETCHING_USER_PATIENT_SUCCESS = 'FETCHING_USER_PATIENT_SUCCESS';
export const FETCHING_USER_PATIENT_FAILURE = 'FETCHING_USER_PATIENT_FAILURE';
export const REMOVE_FETCHING_USER_PATIENT = 'REMOVE_FETCHING_USER_PATIENT';

//Tasks
export const FETCHING_TASKS = 'FETCHING_TASKS';
export const FETCHING_TASKS_SUCCESS = 'FETCHING_TASKS_SUCCESS';
export const FETCHING_TASKS_FAILURE = 'FETCHING_TASKS_FAILURE';
export const REMOVE_FETCHING_TASKS = 'REMOVE_FETCHING_TASKS';
export const UPDATE_NEWTASK_TEXT = 'UPDATE_NEWTASK_TEXT';
export const REMOVE_NEWTASK_TEXT = 'REMOVE_NEWTASK_TEXT';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';

//Assessment
export const FETCHING_ASSESSMENT = 'FETCHING_ASSESSMENT';
export const FETCHING_ASSESSMENT_SUCCESS = 'FETCHING_ASSESSMENT_SUCCESS';
export const FETCHING_ASSESSMENT_FAILURE = 'FETCHING_ASSESSMENT_FAILURE';
export const REMOVE_FETCHING_ASSESSMENT = 'REMOVE_FETCHING_ASSESSMENT';
export const UPDATE_RESPONSE = 'UPDATE_RESPONSE';
export const SUBMIT_RESPONSE = 'SUBMIT_RESPONSE';
export const PROCESSING_RESPONSE_ERROR = 'PROCESSING_RESPONSE_ERROR';
export const CHECK_RESPONSE = 'CHECK_RESPONSE';
export const UPDATE_PERSONAL_INFO = 'UPDATE_PERSONAL_INFO';
export const RETURN_PREVIOUS_QUESTION = 'RETURN_PREVIOUS_QUESTION';

//Patients
export const FETCHING_PATIENT = 'FETCHING_PATIENT';
export const FETCHING_PATIENT_SUCCESS = 'FETCHING_PATIENT_SUCCESS';
export const FETCHING_PATIENT_FAILURE = 'FETCHING_PATIENT_FAILURE';
export const REMOVE_FETCHING_PATIENT = 'REMOVE_FETCHING_PATIENT';
export const UPDATE_CONDITION_INPUT = 'UPDATE_CONDITION_INPUT';
export const TOGGLE_BADGE = 'TOGGLE_BADGE';
export const UPDATE_ASSESSMENT_INPUT = 'UPDATE_ASSESSMENT_INPUT';